// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/proto/v1alpha1/cluster_service.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The unique identifier for the cluster.
	// This field is read-only and is set by the system.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is a human-readable name for the cluster.
	// It can be used for display purposes in user interfaces.
	// This field is optional and can be set by the user.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description provides additional information about the cluster.
	// It can be used to describe the purpose or configuration of the cluster.
	// This field is optional and can be set by the user.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Cluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The cluster to create.
	Cluster       *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type GetClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the cluster to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterRequest) Reset() {
	*x = GetClusterRequest{}
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterRequest) ProtoMessage() {}

func (x *GetClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterRequest.ProtoReflect.Descriptor instead.
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListClustersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of clusters.
	Clusters      []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type DeleteClusterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the cluster to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterRequest) Reset() {
	*x = DeleteClusterRequest{}
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterRequest) ProtoMessage() {}

func (x *DeleteClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_cluster_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_proto_v1alpha1_cluster_service_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_cluster_service_proto_rawDesc = "" +
	"\n" +
	"(api/proto/v1alpha1/cluster_service.proto\x12\x12api.proto.v1alpha1\x1a-api/proto/v1alpha1/longrunningoperation.proto\x1a\x1bgoogle/protobuf/empty.proto\"b\n" +
	"\aCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"M\n" +
	"\x14CreateClusterRequest\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.api.proto.v1alpha1.ClusterR\acluster\"'\n" +
	"\x11GetClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x14ListClustersResponse\x127\n" +
	"\bclusters\x18\x01 \x03(\v2\x1b.api.proto.v1alpha1.ClusterR\bclusters\"*\n" +
	"\x14DeleteClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xfe\x02\n" +
	"\x0eClusterService\x12c\n" +
	"\rCreateCluster\x12(.api.proto.v1alpha1.CreateClusterRequest\x1a(.api.proto.v1alpha1.LongRunningOperation\x12P\n" +
	"\n" +
	"GetCluster\x12%.api.proto.v1alpha1.GetClusterRequest\x1a\x1b.api.proto.v1alpha1.Cluster\x12P\n" +
	"\fListClusters\x12\x16.google.protobuf.Empty\x1a(.api.proto.v1alpha1.ListClustersResponse\x12c\n" +
	"\rDeleteCluster\x12(.api.proto.v1alpha1.DeleteClusterRequest\x1a(.api.proto.v1alpha1.LongRunningOperationBMZKgithub.com/nokamoto/kaas-operator-prototype/pkg/api/proto/v1alpha1;v1alpha1b\x06proto3"

var (
	file_api_proto_v1alpha1_cluster_service_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_cluster_service_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_cluster_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_cluster_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_cluster_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_cluster_service_proto_rawDesc), len(file_api_proto_v1alpha1_cluster_service_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_cluster_service_proto_rawDescData
}

var file_api_proto_v1alpha1_cluster_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1alpha1_cluster_service_proto_goTypes = []any{
	(*Cluster)(nil),              // 0: api.proto.v1alpha1.Cluster
	(*CreateClusterRequest)(nil), // 1: api.proto.v1alpha1.CreateClusterRequest
	(*GetClusterRequest)(nil),    // 2: api.proto.v1alpha1.GetClusterRequest
	(*ListClustersResponse)(nil), // 3: api.proto.v1alpha1.ListClustersResponse
	(*DeleteClusterRequest)(nil), // 4: api.proto.v1alpha1.DeleteClusterRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
	(*LongRunningOperation)(nil), // 6: api.proto.v1alpha1.LongRunningOperation
}
var file_api_proto_v1alpha1_cluster_service_proto_depIdxs = []int32{
	0, // 0: api.proto.v1alpha1.CreateClusterRequest.cluster:type_name -> api.proto.v1alpha1.Cluster
	0, // 1: api.proto.v1alpha1.ListClustersResponse.clusters:type_name -> api.proto.v1alpha1.Cluster
	1, // 2: api.proto.v1alpha1.ClusterService.CreateCluster:input_type -> api.proto.v1alpha1.CreateClusterRequest
	2, // 3: api.proto.v1alpha1.ClusterService.GetCluster:input_type -> api.proto.v1alpha1.GetClusterRequest
	5, // 4: api.proto.v1alpha1.ClusterService.ListClusters:input_type -> google.protobuf.Empty
	4, // 5: api.proto.v1alpha1.ClusterService.DeleteCluster:input_type -> api.proto.v1alpha1.DeleteClusterRequest
	6, // 6: api.proto.v1alpha1.ClusterService.CreateCluster:output_type -> api.proto.v1alpha1.LongRunningOperation
	0, // 7: api.proto.v1alpha1.ClusterService.GetCluster:output_type -> api.proto.v1alpha1.Cluster
	3, // 8: api.proto.v1alpha1.ClusterService.ListClusters:output_type -> api.proto.v1alpha1.ListClustersResponse
	6, // 9: api.proto.v1alpha1.ClusterService.DeleteCluster:output_type -> api.proto.v1alpha1.LongRunningOperation
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_cluster_service_proto_init() }
func file_api_proto_v1alpha1_cluster_service_proto_init() {
	if File_api_proto_v1alpha1_cluster_service_proto != nil {
		return
	}
	file_api_proto_v1alpha1_longrunningoperation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_cluster_service_proto_rawDesc), len(file_api_proto_v1alpha1_cluster_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1alpha1_cluster_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_cluster_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1alpha1_cluster_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_cluster_service_proto = out.File
	file_api_proto_v1alpha1_cluster_service_proto_goTypes = nil
	file_api_proto_v1alpha1_cluster_service_proto_depIdxs = nil
}
