// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/proto/v1alpha1/longrunningoperation.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LongRunningOperation represents a long-running operation in the system.
// It is used to track the status of operations that may take a significant amount of time to complete.
type LongRunningOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The unique identifier for the operation.
	// This field is read-only and is set by the system.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongRunningOperation) Reset() {
	*x = LongRunningOperation{}
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongRunningOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRunningOperation) ProtoMessage() {}

func (x *LongRunningOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRunningOperation.ProtoReflect.Descriptor instead.
func (*LongRunningOperation) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_longrunningoperation_proto_rawDescGZIP(), []int{0}
}

func (x *LongRunningOperation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the operation to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_longrunningoperation_proto_rawDescGZIP(), []int{1}
}

func (x *GetOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of long-running operations.
	Operations    []*LongRunningOperation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1alpha1_longrunningoperation_proto_rawDescGZIP(), []int{2}
}

func (x *ListOperationsResponse) GetOperations() []*LongRunningOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

var File_api_proto_v1alpha1_longrunningoperation_proto protoreflect.FileDescriptor

const file_api_proto_v1alpha1_longrunningoperation_proto_rawDesc = "" +
	"\n" +
	"-api/proto/v1alpha1/longrunningoperation.proto\x12\x12api.proto.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x14LongRunningOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13GetOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\x16ListOperationsResponse\x12H\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2(.api.proto.v1alpha1.LongRunningOperationR\n" +
	"operations2\xd6\x01\n" +
	"\x1bLongRunningOperationService\x12a\n" +
	"\fGetOperation\x12'.api.proto.v1alpha1.GetOperationRequest\x1a(.api.proto.v1alpha1.LongRunningOperation\x12T\n" +
	"\x0eListOperations\x12\x16.google.protobuf.Empty\x1a*.api.proto.v1alpha1.ListOperationsResponseBMZKgithub.com/nokamoto/kaas-operator-prototype/pkg/api/proto/v1alpha1;v1alpha1b\x06proto3"

var (
	file_api_proto_v1alpha1_longrunningoperation_proto_rawDescOnce sync.Once
	file_api_proto_v1alpha1_longrunningoperation_proto_rawDescData []byte
)

func file_api_proto_v1alpha1_longrunningoperation_proto_rawDescGZIP() []byte {
	file_api_proto_v1alpha1_longrunningoperation_proto_rawDescOnce.Do(func() {
		file_api_proto_v1alpha1_longrunningoperation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_longrunningoperation_proto_rawDesc), len(file_api_proto_v1alpha1_longrunningoperation_proto_rawDesc)))
	})
	return file_api_proto_v1alpha1_longrunningoperation_proto_rawDescData
}

var file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1alpha1_longrunningoperation_proto_goTypes = []any{
	(*LongRunningOperation)(nil),   // 0: api.proto.v1alpha1.LongRunningOperation
	(*GetOperationRequest)(nil),    // 1: api.proto.v1alpha1.GetOperationRequest
	(*ListOperationsResponse)(nil), // 2: api.proto.v1alpha1.ListOperationsResponse
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_api_proto_v1alpha1_longrunningoperation_proto_depIdxs = []int32{
	0, // 0: api.proto.v1alpha1.ListOperationsResponse.operations:type_name -> api.proto.v1alpha1.LongRunningOperation
	1, // 1: api.proto.v1alpha1.LongRunningOperationService.GetOperation:input_type -> api.proto.v1alpha1.GetOperationRequest
	3, // 2: api.proto.v1alpha1.LongRunningOperationService.ListOperations:input_type -> google.protobuf.Empty
	0, // 3: api.proto.v1alpha1.LongRunningOperationService.GetOperation:output_type -> api.proto.v1alpha1.LongRunningOperation
	2, // 4: api.proto.v1alpha1.LongRunningOperationService.ListOperations:output_type -> api.proto.v1alpha1.ListOperationsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1alpha1_longrunningoperation_proto_init() }
func file_api_proto_v1alpha1_longrunningoperation_proto_init() {
	if File_api_proto_v1alpha1_longrunningoperation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1alpha1_longrunningoperation_proto_rawDesc), len(file_api_proto_v1alpha1_longrunningoperation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1alpha1_longrunningoperation_proto_goTypes,
		DependencyIndexes: file_api_proto_v1alpha1_longrunningoperation_proto_depIdxs,
		MessageInfos:      file_api_proto_v1alpha1_longrunningoperation_proto_msgTypes,
	}.Build()
	File_api_proto_v1alpha1_longrunningoperation_proto = out.File
	file_api_proto_v1alpha1_longrunningoperation_proto_goTypes = nil
	file_api_proto_v1alpha1_longrunningoperation_proto_depIdxs = nil
}
