apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetescluster-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetescluster-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetescluster-manager-role
subjects:
  - kind: ServiceAccount
    name: kubernetescluster-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetescluster-controller
  namespace: kube-system
  labels:
    app: kubernetescluster-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetescluster-controller
  template:
    metadata:
      labels:
        app: kubernetescluster-controller
    spec:
      containers:
        - name: manager
          image: kind.local/kubernetesclustercontroller:latest
          imagePullPolicy: IfNotPresent
          command:
            - /ko-app/kubernetesclustercontroller
      serviceAccountName: kubernetescluster-controller-manager
