apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetesclusterconfiguration-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetesclusterconfiguration-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetesclusterconfiguration-manager-role
subjects:
  - kind: ServiceAccount
    name: kubernetesclusterconfiguration-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesclusterconfiguration-controller
  namespace: kube-system
  labels:
    app: kubernetesclusterconfiguration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetesclusterconfiguration-controller
  template:
    metadata:
      labels:
        app: kubernetesclusterconfiguration-controller
    spec:
      containers:
        - name: manager
          image: kind.local/kubernetesclusterconfigurationcontroller:latest
          imagePullPolicy: IfNotPresent
          command:
            - /ko-app/kubernetesclusterconfigurationcontroller
      serviceAccountName: kubernetesclusterconfiguration-controller-manager
