// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/proto/v1alpha1/cluster_service.proto

package v1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1alpha1 "github.com/nokamoto/kaas-operator-prototype/pkg/api/proto/v1alpha1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClusterServiceName is the fully-qualified name of the ClusterService service.
	ClusterServiceName = "api.proto.v1alpha1.ClusterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClusterServiceCreateClusterProcedure is the fully-qualified name of the ClusterService's
	// CreateCluster RPC.
	ClusterServiceCreateClusterProcedure = "/api.proto.v1alpha1.ClusterService/CreateCluster"
	// ClusterServiceGetClusterProcedure is the fully-qualified name of the ClusterService's GetCluster
	// RPC.
	ClusterServiceGetClusterProcedure = "/api.proto.v1alpha1.ClusterService/GetCluster"
	// ClusterServiceListClustersProcedure is the fully-qualified name of the ClusterService's
	// ListClusters RPC.
	ClusterServiceListClustersProcedure = "/api.proto.v1alpha1.ClusterService/ListClusters"
	// ClusterServiceDeleteClusterProcedure is the fully-qualified name of the ClusterService's
	// DeleteCluster RPC.
	ClusterServiceDeleteClusterProcedure = "/api.proto.v1alpha1.ClusterService/DeleteCluster"
)

// ClusterServiceClient is a client for the api.proto.v1alpha1.ClusterService service.
type ClusterServiceClient interface {
	// CreateCluster creates a new cluster.
	// It returns a LongRunningOperation that can be used to track the progress of the operation.
	CreateCluster(context.Context, *connect.Request[v1alpha1.CreateClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error)
	// GetCluster retrieves the details of a specific cluster by its name.
	GetCluster(context.Context, *connect.Request[v1alpha1.GetClusterRequest]) (*connect.Response[v1alpha1.Cluster], error)
	// ListClusters lists all clusters.
	ListClusters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListClustersResponse], error)
	// DeleteCluster deletes a specific cluster by its name.
	// It returns a LongRunningOperation that can be used to track the progress of the operation.
	DeleteCluster(context.Context, *connect.Request[v1alpha1.DeleteClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error)
}

// NewClusterServiceClient constructs a client for the api.proto.v1alpha1.ClusterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClusterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClusterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clusterServiceMethods := v1alpha1.File_api_proto_v1alpha1_cluster_service_proto.Services().ByName("ClusterService").Methods()
	return &clusterServiceClient{
		createCluster: connect.NewClient[v1alpha1.CreateClusterRequest, v1alpha1.LongRunningOperation](
			httpClient,
			baseURL+ClusterServiceCreateClusterProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("CreateCluster")),
			connect.WithClientOptions(opts...),
		),
		getCluster: connect.NewClient[v1alpha1.GetClusterRequest, v1alpha1.Cluster](
			httpClient,
			baseURL+ClusterServiceGetClusterProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("GetCluster")),
			connect.WithClientOptions(opts...),
		),
		listClusters: connect.NewClient[emptypb.Empty, v1alpha1.ListClustersResponse](
			httpClient,
			baseURL+ClusterServiceListClustersProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("ListClusters")),
			connect.WithClientOptions(opts...),
		),
		deleteCluster: connect.NewClient[v1alpha1.DeleteClusterRequest, v1alpha1.LongRunningOperation](
			httpClient,
			baseURL+ClusterServiceDeleteClusterProcedure,
			connect.WithSchema(clusterServiceMethods.ByName("DeleteCluster")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clusterServiceClient implements ClusterServiceClient.
type clusterServiceClient struct {
	createCluster *connect.Client[v1alpha1.CreateClusterRequest, v1alpha1.LongRunningOperation]
	getCluster    *connect.Client[v1alpha1.GetClusterRequest, v1alpha1.Cluster]
	listClusters  *connect.Client[emptypb.Empty, v1alpha1.ListClustersResponse]
	deleteCluster *connect.Client[v1alpha1.DeleteClusterRequest, v1alpha1.LongRunningOperation]
}

// CreateCluster calls api.proto.v1alpha1.ClusterService.CreateCluster.
func (c *clusterServiceClient) CreateCluster(ctx context.Context, req *connect.Request[v1alpha1.CreateClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error) {
	return c.createCluster.CallUnary(ctx, req)
}

// GetCluster calls api.proto.v1alpha1.ClusterService.GetCluster.
func (c *clusterServiceClient) GetCluster(ctx context.Context, req *connect.Request[v1alpha1.GetClusterRequest]) (*connect.Response[v1alpha1.Cluster], error) {
	return c.getCluster.CallUnary(ctx, req)
}

// ListClusters calls api.proto.v1alpha1.ClusterService.ListClusters.
func (c *clusterServiceClient) ListClusters(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListClustersResponse], error) {
	return c.listClusters.CallUnary(ctx, req)
}

// DeleteCluster calls api.proto.v1alpha1.ClusterService.DeleteCluster.
func (c *clusterServiceClient) DeleteCluster(ctx context.Context, req *connect.Request[v1alpha1.DeleteClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error) {
	return c.deleteCluster.CallUnary(ctx, req)
}

// ClusterServiceHandler is an implementation of the api.proto.v1alpha1.ClusterService service.
type ClusterServiceHandler interface {
	// CreateCluster creates a new cluster.
	// It returns a LongRunningOperation that can be used to track the progress of the operation.
	CreateCluster(context.Context, *connect.Request[v1alpha1.CreateClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error)
	// GetCluster retrieves the details of a specific cluster by its name.
	GetCluster(context.Context, *connect.Request[v1alpha1.GetClusterRequest]) (*connect.Response[v1alpha1.Cluster], error)
	// ListClusters lists all clusters.
	ListClusters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListClustersResponse], error)
	// DeleteCluster deletes a specific cluster by its name.
	// It returns a LongRunningOperation that can be used to track the progress of the operation.
	DeleteCluster(context.Context, *connect.Request[v1alpha1.DeleteClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error)
}

// NewClusterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClusterServiceHandler(svc ClusterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clusterServiceMethods := v1alpha1.File_api_proto_v1alpha1_cluster_service_proto.Services().ByName("ClusterService").Methods()
	clusterServiceCreateClusterHandler := connect.NewUnaryHandler(
		ClusterServiceCreateClusterProcedure,
		svc.CreateCluster,
		connect.WithSchema(clusterServiceMethods.ByName("CreateCluster")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServiceGetClusterHandler := connect.NewUnaryHandler(
		ClusterServiceGetClusterProcedure,
		svc.GetCluster,
		connect.WithSchema(clusterServiceMethods.ByName("GetCluster")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServiceListClustersHandler := connect.NewUnaryHandler(
		ClusterServiceListClustersProcedure,
		svc.ListClusters,
		connect.WithSchema(clusterServiceMethods.ByName("ListClusters")),
		connect.WithHandlerOptions(opts...),
	)
	clusterServiceDeleteClusterHandler := connect.NewUnaryHandler(
		ClusterServiceDeleteClusterProcedure,
		svc.DeleteCluster,
		connect.WithSchema(clusterServiceMethods.ByName("DeleteCluster")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.proto.v1alpha1.ClusterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClusterServiceCreateClusterProcedure:
			clusterServiceCreateClusterHandler.ServeHTTP(w, r)
		case ClusterServiceGetClusterProcedure:
			clusterServiceGetClusterHandler.ServeHTTP(w, r)
		case ClusterServiceListClustersProcedure:
			clusterServiceListClustersHandler.ServeHTTP(w, r)
		case ClusterServiceDeleteClusterProcedure:
			clusterServiceDeleteClusterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClusterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClusterServiceHandler struct{}

func (UnimplementedClusterServiceHandler) CreateCluster(context.Context, *connect.Request[v1alpha1.CreateClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.v1alpha1.ClusterService.CreateCluster is not implemented"))
}

func (UnimplementedClusterServiceHandler) GetCluster(context.Context, *connect.Request[v1alpha1.GetClusterRequest]) (*connect.Response[v1alpha1.Cluster], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.v1alpha1.ClusterService.GetCluster is not implemented"))
}

func (UnimplementedClusterServiceHandler) ListClusters(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha1.ListClustersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.v1alpha1.ClusterService.ListClusters is not implemented"))
}

func (UnimplementedClusterServiceHandler) DeleteCluster(context.Context, *connect.Request[v1alpha1.DeleteClusterRequest]) (*connect.Response[v1alpha1.LongRunningOperation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.v1alpha1.ClusterService.DeleteCluster is not implemented"))
}
