apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesclusterconfiguration-manager-role
rules:
  - apiGroups:
      - nokamoto.github.com
    resources:
      - kubernetesclusterconfigurations
      - kubernetesclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nokamoto.github.com
    resources:
      - kubernetesclusterconfigurations/status
    verbs:
      - get
      - patch
      - update
