apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-manager-role
rules:
  - apiGroups:
      - nokamoto.github.com
    resources:
      - kubernetesclusters
      - pipelines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nokamoto.github.com
    resources:
      - pipelines/status
    verbs:
      - get
      - patch
      - update
